---
title: "Catboost"
author: "Serkan Oral"
date: '2022-05-27'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(tidymodels)
library(naniar)
library(skimr)
library(patchwork)
library(vip)
remotes::install_github("Glemhel/treesnip")
library(treesnip)
library(finetune)
library(vip)
```

```{r}
train_data <- read_csv("Data/train.csv")
test_data <- read_csv("Data/test.csv")
sample <- read_csv("Data/sample_submission.csv")

train <- train_data %>% 
  mutate(Cabin_original = Cabin) %>% 
  separate(Name, into =c("First_name", "Last_name")) %>% 
  separate(Cabin, into = c("Cabin_1", "Cabin_2", "Cabin_3" )) %>% 
  mutate_if(is.character, factor)




train %>% 
  drop_na(Last_name) %>% 
  filter(Last_name == "Barbes") %>% 
  count(Transported)


test <- test_data %>% 
  mutate(Cabin_original = Cabin) %>% 
  separate(Name, into =c("First_name", "Last_name")) %>% 
  separate(Cabin, into = c("Cabin_1", "Cabin_2", "Cabin_3" )) %>% 
  mutate_if(is.character, factor)


train$Transported <- as.factor(train$Transported)
train$CryoSleep <- as.factor(train$CryoSleep)
train$VIP <- as.factor(train$VIP)

test$CryoSleep <- as.factor(test$CryoSleep)
test$VIP <- as.factor(test$VIP)

set.seed(123)
split <- initial_split(train, strata = Transported)
train_t <- training(split)
test_t <- testing(split)
```




Recipe

What to do with NA values
AGE - Random Forest
ROOMSERVICE - 3 - maybe log transformation +1
Destination - "PSO J318.5-2255"
Foodcourt - 0 - maybe log transformation +1
SPA - 2 - maybe log transformation +1
VRDeck - 6 - maybe log transformation +1
CABIN_1 - A
CABIN_2 - "269"
CABIN_3 - KNN
Cabin_original - CABIN_1+ CABIN_2 + CABIN_3
HomePlanet - Mars
VIP - TRUE
ShoppingMall - 0 - maybe log transformation +1
Cryosleep - FALSE



```{r}
set.seed(123)
rec <- train_t %>%
recipe(Transported ~.)%>%
step_novel(all_nominal_predictors()) %>% 
step_unknown(First_name,Last_name) %>% 
step_impute_bag(all_numeric_predictors()) %>% 
step_impute_knn(all_nominal_predictors(),neighbors = 5) %>% 
# step_YeoJohnson(RoomService, FoodCourt,Spa, VRDeck,ShoppingMall) %>% 
step_normalize(all_numeric_predictors()) %>% 
step_nzv(all_predictors()) 

  
  
```




```{r}
preped_rec <- rec %>% prep()
preped_rec %>% bake(new_data = NULL) 

```

```{r}
cat_spec <- boost_tree(trees = 1000,min_n = tune(),learn_rate = tune(),
                       tree_depth = tune()) %>%
set_engine("catboost", loss_function = 'Logloss')%>%
set_mode("classification")


# cat_spec <- boost_tree(trees = 1000,min_n = 20,learn_rate = 0.0215,
#                        tree_depth = 7) %>%
# set_engine("catboost", loss_function = 'Logloss')%>%
# set_mode("classification")



# Some alternatives
# min_n = 34 learn_rate = 0.0216
# min_n = 25 learn_rate = 0.0650
# min_n = 11 learn_rate = 0.0158

# Some alternatives
# min_n = 20 tree_depth = 7 learn_rate = 0.0215
# min_n = 40 tree_depth = 13 learn_rate = 0.0659
# min_n = 7  tree_depth = 8 learn_rate = 0.0879


# Some alternatives
# min_n = 8 tree_depth = 12 learn_rate = 0.0675
# min_n = 17 tree_depth = 5 learn_rate = 0.00905
# min_n = 21  tree_depth = 13 learn_rate = 0.0041


```


```{r}
cat_wf <- workflow() %>%
add_recipe(rec,blueprint = hardhat::default_recipe_blueprint(allow_novel_levels = TRUE))%>%
add_model(cat_spec)
```

```{r}
set.seed(234)
cat_grid <- grid_max_entropy(min_n(), learn_rate(),tree_depth(), size = 25) %>% 
  round(8)

seq(0.0215,0.01)
```

```{r}
set.seed(123)
kfold <- vfold_cv(train_t)

doParallel::registerDoParallel()

set.seed(234)
cat_res <- tune_grid(object = cat_wf,resamples = kfold,grid = cat_grid,control = control_grid(save_pred = TRUE),metrics = metric_set(accuracy))

cat_final_wf <- finalize_workflow(cat_wf, select_best(cat_res))
```


```{r}

doParallel::registerDoParallel()

cat_fit <- fit(cat_final_wf, train)

# doParallel::registerDoParallel()
# 
# cat_fit <- fit(cat_final_wf, train)
```


```{r}

predict(cat_fit, test_t) %>% 
  bind_cols(test_t) %>% 
  select(.pred_class, Transported) %>% 
  conf_mat(Transported, .pred_class)
```

```{r}

set.seed(123)
submission <- predict(cat_fit, test) %>% 
  bind_cols(test) %>% 
  select(PassengerId, .pred_class) %>% 
  rename(Transported = .pred_class)

submission$PassengerId <- as.character(submission$PassengerId)
submission$Transported <- str_to_title(as.character(submission$Transported))

write_csv(submission,file = "Submission.csv")
```





